# Generated by Django 5.1.4 on 2025-01-05 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetario', '0002_alter_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(choices=[('F', 'Fácil'), ('M', 'Medio'), ('D', 'Difícil')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
